const recipeOptions = [
    'Chicken Alfredo',
    'Lasagna',
    'Spaghetti Bolognese',
    'Stir-Fry',
    'Risotto',
    'Caesar Salad',
    'BBQ Pulled Pork Sandwich',
    'Shrimp Scampi',
    'Pizza',
    'Beef Tacos',
    'Caprese Salad',
    'Chocolate Chip Cookies',
    'Lemon Garlic Roasted Chicken',
    'Pasta Primavera',
    'Tomato Basil Soup',
    'Grilled Cheese Sandwich',
    'Pad Thai',
    'Omelette',
    'Beef Stroganoff',
    'Hawaiian Pizza',
    'Crispy Fried Chicken',
    'Eggplant Parmesan',
    'Minestrone Soup',
    'Avocado Toast',
    'Chocolate Brownies',
    'Pancakes',
 
  
  
  
  'Cajun Jambalaya',
  'Grilled Portobello Mushrooms',
  'Chickpea Curry',
  'Lobster Bisque',
  'Pineapple Fried Rice',
  'Tandoori Chicken',
  'Baked Ziti',
  'French Onion Soup',
 
  'Shrimp and Grits',
  'Chicken Katsu',
  'Cobb Salad',
  'Sushi Rolls',
  'Vegetable Curry',
  'Clam Chowder',
  'Chicken Fajitas',
  'Beef Tendon Noodle Soup',
  'Sweet and Sour Tofu',
  'Chocolate Mousse',
  'Sesame Ginger Noodles',
  'Lentil Soup',
  'Crispy Pork Belly',
  
  'Pumpkin Pie',
  'Peach Cobbler',
  'Coq au Vin',
  'Spinach and Artichoke Dip',
  'Lemon Meringue Pie',
  'Egg Drop Soup',
  'Fajita Bowl',
  'Chicken Parmesan',
  'Blueberry Pancakes',
  'Miso Soup',
  'Chicken Satay',
  'Sausage and Peppers',
  'Avocado Smoothie',
  'Tomato Bruschetta',
  'Lemon Bars',
  'Cherry Pie',
  'Pad See Ew',
  'Tom Kha Gai',
  'Caramel Flan',
  'Strawberry Shortcake',
  'Hummus and Pita',
  'Samosas',
  'Roast Duck',
  'Shrimp and Spinach Salad',
  'Spicy Tofu Noodles',
  'Chicken Enchiladas',
  'Lemon Butter Shrimp',
  'Ginger Chicken Stir-Fry',
  'Baked Alaska',
  'Pumpkin Soup',
  'Black Bean Tacos',
  'Lentil Curry',
  'Chicken and Rice Casserole',
  'Blueberry Muffins',
  'Tofu Tikka Masala',
  'Baklava',
  'Banana Split',
  'Bacon-Wrapped Scallops',
  'Tomato Bisque',
  'Coconut Shrimp',
  'Spinach Stuffed Mushrooms',
  'Eggplant Rollatini',
  'Peach Melba',
  'Mushroom Fettuccine Alfredo',
  'Cinnamon Rolls',
  'Chicken and Dumplings',
  'Key Lime Pie',
  'Sesame Chicken',
  'Chili Con Carne',
  'Lemon Poppy Seed Muffins',
  'Tofu Scramble',
  'Pepperoni Pizza',
  'Steak Diane',
  'Pecan Pie',
  'Pineapple Upside-Down Cake',
  'Tofu and Vegetable Stir-Fry',
  'Ratatouille',
  'Potato Leek Soup',
  'Chocolate Eclairs',
  'Greek Salad',
  'Shrimp Po Boy',
  'Beef and Noodles',
  'Caramel Apples',
  'Lemon Sorbet',
  'Pasta Carbonara',
  'Egg Fried Rice',
  'Chow Mein',
  'Mint Chocolate Chip Ice Cream',
  'Beef Wellington',
  'Tofu Tacos',
  'Baked Macaroni and Cheese',
  'Chocolate Truffles',
  'Sausage and Mushroom Risotto',
  'Cinnamon Swirl Bread',
  'Honey Garlic Chicken',
  'Chicken and Waffles',
  'Pumpkin Cheesecake',
  'Vegetable Tempura',
  'Tomato Mozzarella Panini',
  'Creamed Spinach',
  'Tofu Kebabs',
  'Beef and Black Bean Sauce',
  'Lemon Chicken Piccata',
  'Pumpkin Bread',
  'Cranberry Sauce',
  'Sweet Potato Casserole',
  'Tofu Spring Rolls',
  'Rice Pudding',
  'Beef Tamales',
  'Chocolate Fondue',
  'Tandoori Shrimp',
  'Broccoli Cheddar Soup',
  'Baked Chicken Parmesan',
  'Pineapple Coconut Smoothie',
  'Beef Empanadas',
  'Chocolate Lava Cake',
  'Lemon Ricotta Pancakes',
  'Potato Latkes',
  'Tofu Stroganoff',
  'Beef Gyros',
  'Cream of Asparagus Soup',
  'Tofu BLT Sandwich',
  'Mushroom Barley Soup',
  'Caramelized Onion Quiche',
  'Lemon Garlic Shrimp',
  'Peach Crisp',
  'Beef Lo Mein',
  'Chocolate Banana Bread',
  'Chicken Quesadillas',
  'Black Bean Soup',
  'Gingerbread Cookies',
  'Baked Chicken Alfredo',
  'Pasta Aglio e Olio',
  'Tofu and Broccoli Stir-Fry',
  'Mango Chutney',
  'Tofu Fajitas',
  'Chicken Marsala',
  'Key Lime Bars',
  'Chicken Pesto Pasta',
  'Peach Sorbet',
  'Lemon Thyme Chicken',
  'Cajun Chicken Pasta',
  'Spicy Tofu Tacos',
  'Beef and Potato Curry',
  'Creme Brulee',
  'Banana Foster',
  'Chicken Tikka',
  'Mango Lassi',
  'Garlic Butter Shrimp',
  'Peach Cobbler',
  'Beef and Vegetable Stir-Fry',
  'Chocolate Covered Strawberries',
  'Chicken Pot Pie',
  'Pasta Primavera',
  'Tofu Tikka Wrap',
  'Miso Ramen',
  'Pineapple Teriyaki Chicken',
  'Tofu and Mushroom Risotto',
  'Tomato Pesto Pasta',
  'Lemon Garlic Roasted Shrimp',
  'Cajun Fries',
  'Mushroom and Spinach Quesadilla',
  'Beef and Noodle Soup',
  'Chocolate Mousse Cake',
  'Lemon Raspberry Bars',
  'Eggplant Lasagna',
  'Peach Smoothie',
  'Tofu and Spinach Salad',
  'Rice and Beans',
  'Baked Potato Soup',
  'Sesame Crusted Tofu',
  'Garlic Parmesan Shrimp',
  'Chocolate Cherry Pie',
  'Chicken and Rice Soup',
  'Key Lime Cheesecake',
  'Chicken Enchilada Casserole',
  'Pasta with Clam Sauce',
  'Mango Salsa',
  'Pineapple Sorbet',
  'Tofu and Rice Bowl',
  'Miso Glazed Salmon',
  'Beef Tostadas',
  'Lemon Bars',
  'Eggplant Parmesan Sandwich',
  'Peach Pie',
  'Tofu and Noodle Stir-Fry',
  'Chocolate Eclair Cake',
  'Lemon Poppy Seed Bread',
  'Black Bean Enchiladas',
  'Cinnamon Apple Pie',
  'Beef and Broccoli Soup',
  'Pineapple Coconut Cake',
  'Tofu and Vegetable Curry',
  'Tofu and Rice Paper Rolls',
  'Mushroom and Spinach Stuffed Chicken',
  'Beef and Peppers Stir-Fry',
  'Chocolate Coconut Macaroons',
  'Garlic Butter Shrimp Scampi',
  'Lemon Herb Roasted Chicken',
  'Cajun Shrimp and Grits',
  'Pasta with Pesto Sauce',
  'Mango and Banana Smoothie',
  'Pineapple Upside-Down Pancakes',
  'Tofu and Vegetable Stir-Fry',
  'Tomato Basil Bruschetta',
  'Peach and Blueberry Crisp',
  'Tofu and Vegetable Tempura',
  'Mushroom and Spinach Lasagna',
  'Beef and Broccoli Noodles',
  'Chocolate Chip Pancakes',
  'Lemon Garlic Butter Salmon',
  'Eggplant and Zucchini Parmesan',
  'Pumpkin Pancakes',
  'Tomato and Cucumber Salad',
  'Beef and Bean Burritos',
  'Chocolate Mint Brownies',
  'Cajun Seafood Boil',
  'Sesame Noodles',
  'Garlic Roasted Shrimp',
  'Lemon Blueberry Cake',
  'Chicken and Rice Casserole',
  'Key Lime Cupcakes',
  'Tofu and Rice Noodles',
  'Mango Pineapple Salsa',
  'Pineapple Teriyaki Tofu',
  'Beef and Vegetable Curry',
  'Chocolate Chip Oatmeal Cookies',
  'Chicken Tenders',
  'Pasta Carbonara',
  'Tofu and Quinoa Salad',
  'Miso-Glazed Eggplant',
  'Beef and Mushroom Gravy',
  'Lemon Coconut Cake',
  'Eggplant and Tomato Ratatouille',
  'Peach and Raspberry Pie',
  'Tofu and Vegetable Ramen',
  'Rice and Vegetable Stir-Fry',
  'Chocolate Cherry Trifle',
  'Lemon Cilantro Shrimp',
  'Cajun Chicken and Rice',
  'Spaghetti Carbonara',
  'Tofu and Peanut Sauce',
  'Tomato and Mozzarella Salad',
  'Pineapple Coconut Smoothie Bowl',
  'Beef and Vegetable Stir-Fry',
  'Chocolate Dipped Strawberries',
  'Chicken Alfredo Pizza',
  'Key Lime Cheesecake Bars',
  'Tofu and Coconut Curry',
  'Mushroom and Spinach Risotto',
  'Lemon Herb Roasted Shrimp',
  'Cajun Blackened Salmon',
  'Pasta Aglio e Olio',
  'Mango and Avocado Salad',
  'Pineapple Banana Smoothie',
  'Beef and Potato Skillet',
  'Chocolate Chip Cookie Dough',
  'Chicken Tacos',
  'Cinnamon Sugar Donuts',
  'Garlic Parmesan Shrimp Pasta',
  'Lemon Garlic Roasted Asparagus',
  'Eggplant Caponata',
  'Peach and Blackberry Cobbler',
  'Tofu and Sweet Potato Curry',
  'Beef and Potato Hash',
  'Tofu and Avocado Salad',
  'Mushroom and Spinach Frittata',
  'Spaghetti with Garlic and Oil',
  'Chocolate Pecan Pie',
  'Lemon Garlic Roasted Potatoes',
  'Cajun Chicken and Sausage Gumbo',
  'Pasta with Alfredo Sauce',
  'Mango Coconut Rice',
  'Pineapple Mango Smoothie',
  'Beef and Potato Tacos',
  'Tofu and Edamame Salad',
  'Beef and Potato Curry',
  'Chocolate Covered Pretzels',
  'Chicken Shawarma',
  'Cinnamon Swirl Pancakes',
  'Garlic Parmesan Roasted Asparagus',
  'Lemon Pepper Shrimp',
  'Eggplant Roll-Ups',
  'Peach and Strawberry Smoothie',
  'Tofu and Pineapple Stir-Fry',
  'Beef and Bean Chili',
  'Tofu and Coconut Soup',
  'Mushroom and Spinach Omelette',
  'Beef and Broccoli Noodle Bowl',
  'Chocolate Chip Waffles',
  'Chicken Caesar Wrap',
  'Key Lime Ice Cream',
  'Pasta with Vodka Sauce',
  'Mango Salsa',
  'Pineapple Mango Salad',
  'Beef and Vegetable Skewers',
  'Chocolate Peanut Butter Cups',
  'Chicken and Bacon Wrap',
  'Tofu and Rice Soup',
  'Tomato Basil Risotto',
  'Lemon Blueberry Muffins',
  'Beef and Potato Pie',
  'Tofu and Kale Salad',
  'Mushroom and Spinach Stuffed Peppers',
  'Chicken and Black Bean Soup',
  'Cajun Salmon',
  'Pasta with Pesto',
  'Tofu and Lemongrass Curry',
  'Tomato Caprese Salad',
  'Pineapple Coconut Sorbet',
  'Beef and Potato Tostadas',
  'Chocolate Dipped Fruit',
  'Chicken and Broccoli Stir-Fry',
  'Lemon Garlic Roasted Brussels Sprouts',
  'Eggplant and Zucchini Stir-Fry',
  'Peach Melba Ice Cream',
  'Tofu and Shiitake Mushrooms',
  'Rice and Quinoa Bowl',
  'Black Bean and Corn Salad',
  'Garlic Butter Shrimp Scampi',
  'Chocolate Raspberry Truffle Cake',
  'Chicken and Vegetable Curry',
  'Miso Soup',
  'Pasta Alfredo',
  'Tofu and Noodle Soup',
  'Tomato and Basil Pesto',
  'Pineapple Coconut Muffins',
  'Beef and Potato Casserole',
  'Chocolate Caramel Brownies',
  'Chicken Fajita Bowl',
  'Lemon Garlic Roasted Asparagus',
  'Eggplant and Tomato Curry',
  'Peach and Cherry Galette',
  'Tofu and Kimchi Stir-Fry',
  'Beef and Vegetable Noodles',
  'Mango Banana Bread',
  'Cajun Shrimp Tacos',
  'Spaghetti with Meatballs',
  'Cinnamon Swirl Coffee Cake',
  'Garlic Parmesan Roasted Potatoes',
  'Lemon Thyme Roasted Chicken',
  'Eggplant Parmesan Lasagna',
  'Peach Cobbler Ice Cream',
  'Tofu and Vegetable Quiche',
  'Beef and Potato Stew',
  'Tofu and Rice Paper Wraps',
  'Mushroom and Spinach Quesadillas',
  'Beef and Black Bean Tacos',
  'Chocolate Mocha Cake',
  'Chicken and Rice Stir-Fry',
  'Key Lime Pie Ice Cream',
  'Pasta with Tomato Sauce',
  'Mango and Pineapple Smoothie',
  'Pineapple Teriyaki Salmon',
  'Beef and Vegetable Curry Bowl',
  'Chocolate Banana Smoothie',
  'Chicken and Vegetable Soup',
  'Cinnamon Swirl French Toast',
  'Garlic Parmesan Roasted Brussels Sprouts',
  'Lemon Basil Grilled Chicken',
  'Eggplant and Tomato Pizza',
  'Peach and Raspberry Crisp',
  'Tofu and Vegetable Sushi',
  'Rice and Vegetable Pilaf',
  'Black Bean and Avocado Salad',
  'Garlic Butter Shrimp and Pasta',
  'Chocolate Hazelnut Brownies',
  'Chicken and Broccoli Rice Bowl',
  'Miso-Glazed Salmon',
  'Pasta with Creamy Alfredo',
  'Tofu and Seaweed Salad',
  'Tomato Basil Pesto Pasta',
  'Pineapple and Mango Smoothie Bowl',
  'Beef and Vegetable Stir-Fry',
  'Chocolate Covered Marshmallows',
  'Chicken and Vegetable Wrap',
  'Key Lime Pie Bars',
  'Tofu and Vegetable Pad Thai',
  'Mushroom and Spinach Stuffed Mushrooms',
  'Beef and Broccoli Curry',
  'Tofu and Vegetable Spring Rolls',
  'Chocolate Chip Cookies and Cream',
  'Garlic Parmesan Shrimp and Pasta',
  'Lemon Garlic Butter Asparagus',
  'Eggplant Caponata Sandwich',
  'Peach and Strawberry Sorbet',
  'Tofu and Pineapple Fried Rice',
  'Beef and Vegetable Noodle Stir-Fry',
  'Cajun Shrimp and Rice',
  'Spaghetti with Clam Sauce',
  'Cinnamon Swirl Muffins',
  'Mushroom and Spinach Risotto',
  'Tomato Basil Bruschetta',
  'Pineapple Coconut Cake',
  'Beef and Potato and Vegetable Curry',
  'Chocolate Chip Oatmeal Pancakes',
  'Lemon Garlic Butter Roasted Shrimp',
  'Cajun Chicken Pasta',
  'Pasta with Alfredo Sauce',
  'Tofu and Quinoa Bowl',
  'Tomato Pesto Bruschetta',
  'Peach and Blackberry Cobbler',
  'Tofu and Sweet Potato and Vegetable Curry',
  'Beef and Potato Hash and Vegetable Skewers',
  'Tofu and Avocado and Vegetable Salad',
  'Mushroom and Spinach Frittata',
  'Spaghetti with Garlic and Oil',
  'Chocolate Pecan Pie and Roasted Potatoes',
  'Lemon Herb Roasted Brussels Sprouts',
  'Cajun Blackened Salmon and Vegetable Gumbo',
  'Pasta with Pesto Sauce',
  'Tofu and Lemongrass Curry',
  'Tomato Caprese Salad',
  'Pineapple Coconut Sorbet',
  'Beef and Potato Tostadas',
  'Chocolate Dipped Fruit',
  ];
  
  export default recipeOptions;
  